### ISSUE TITLE
The argument `capture` never works.

### ISSUE THREAD

**Issue by HenryYan2012** [nickschot/ember-gesture-modifiers#28]
`this.useCapture` is not defined in `addon/modifiers/did-pan.js`, So, the argument `capture` never works.
```js
    this.element.addEventListener('pointerdown', this.didTouchStart, { capture: this.useCapture, passive: true });
```

**Comment by nickschot** [comment]
Ah this seems to be a bug, we should replace this.useCapture with this.capture and add some tests for it.
