### ISSUE TITLE
v2 addonification 

### ISSUE THREAD

**Issue by NullVoxPopuli** [nickschot/ember-gesture-modifiers#537]
Is this library interested?

I'd like to include ember-mobile menu in universal-ember, but all addons must be in the v2 formt.

Thanks!

**Comment by nickschot** [comment]
Yes! I'm still busy with mobile menu itself. Feel free to convert this one in the meantime.

**Comment by nickschot** [comment]
This was resolved in the latest release through https://github.com/nickschot/ember-gesture-modifiers/pull/556
